"""
OmniScribe MCP/API Integration Layer
Pushes generated assets to external tools via their APIs.
All functions are independent — failure in one never breaks others.
"""
import os
import json
import requests
from datetime import datetime
from dotenv import load_dotenv
load_dotenv()


def get_integration_status() -> dict:
    from backend.vault import get_all_oauth_status

    connected = get_all_oauth_status()
    return {
        "notion": "notion" in connected,
        "jira":   "jira" in connected,
        "github": "github" in connected,
        "slack":  "slack" in connected,
    }


# ── NOTION ────────────────────────────────────────────────────────────────────

def push_to_notion(brief_content: str, tickets: list, session_id: str) -> dict:
    """
    Push meeting brief and tickets to a Notion database or page.
    Requires: NOTION_TOKEN and NOTION_PAGE_ID in .env
    Get token: notion.so/my-integrations → Create integration → copy secret
    Get page ID: open your Notion page → share → copy link → ID is the last 32 chars
    """
    from backend.vault import get_oauth_token

    tok = get_oauth_token("notion")
    if not tok:
        return {"success": False, "error": "Notion not connected. Use the Connections tab."}
    token = tok["access_token"]
    extra = json.loads(tok.get("extra_data") or "{}")
    page_id = os.getenv("NOTION_PAGE_ID") or extra.get("workspace_id") or ""

    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28"
    }

    parent_data = {"page_id": page_id}
    client_id = os.getenv("NOTION_CLIENT_ID", "")

    # Search API fallback: if parent page is empty, matches client_id placeholder, or is missing
    if not page_id or page_id == client_id:
        try:
            search_resp = requests.post(
                "https://api.notion.com/v1/search",
                headers=headers,
                json={"page_size": 1},
                timeout=10
            )
            if search_resp.status_code == 200:
                results = search_resp.json().get("results", [])
                if results:
                    obj_type = results[0].get("object")
                    obj_id = results[0].get("id")
                    if obj_type == "database":
                        parent_data = {"database_id": obj_id}
                    elif obj_type == "page":
                        parent_data = {"page_id": obj_id}
        except Exception:
            pass

    # Build ticket blocks
    ticket_blocks = []
    for t in tickets:
        p = t.get("priority", "P2")
        color = {"P1": "red", "P2": "orange", "P3": "blue"}.get(p, "gray")
        ticket_blocks.append({
            "object": "block",
            "type": "callout",
            "callout": {
                "rich_text": [{"type": "text", "text": {"content": f"[{t.get('id','')}] {t['title']}"}}],
                "icon": {"emoji": {"P1": "🔴", "P2": "🟠", "P3": "🟡"}.get(p, "⚪")},
                "color": f"{color}_background"
            }
        })
        ticket_blocks.append({
            "object": "block",
            "type": "paragraph",
            "paragraph": {
                "rich_text": [{"type": "text", "text": {
                    "content": f"Priority: {p} | Type: {t.get('ticket_type','task')} | Assignee: {t.get('assignee','Unassigned')}\n{t['description']}"
                }}]
            }
        })

    page_data = {
        "parent": parent_data,
        "properties": {
            "title": {"title": [{"text": {"content": f"Meeting Brief — {session_id} — {datetime.now().strftime('%d %b %Y')}"}}]}
        },
        "children": [
            {"object": "block", "type": "heading_2",
             "heading_2": {"rich_text": [{"type": "text", "text": {"content": "Meeting Summary"}}]}},
            {"object": "block", "type": "paragraph",
             "paragraph": {"rich_text": [{"type": "text", "text": {"content": brief_content[:1800]}}]}},
            {"object": "block", "type": "divider", "divider": {}},
            {"object": "block", "type": "heading_2",
             "heading_2": {"rich_text": [{"type": "text", "text": {"content": f"Action Items ({len(tickets)} tickets)"}}]}},
            *ticket_blocks,
            {"object": "block", "type": "divider", "divider": {}},
            {"object": "block", "type": "callout",
             "callout": {
                 "rich_text": [{"type": "text", "text": {"content": f"Generated by OmniScribe Gatekeeper · Session {session_id} · Secrets sanitized locally before processing"}}],
                 "icon": {"emoji": "🛡"},
                 "color": "green_background"
             }}
        ]
    }

    response = requests.post(
        "https://api.notion.com/v1/pages",
        headers=headers,
        json=page_data
    )

    if response.status_code == 200:
        data = response.json()
        return {"success": True, "url": data.get("url", ""), "id": data.get("id", "")}
    else:
        err_msg = response.text
        try:
            err_data = response.json()
            if err_data.get("code") == "object_not_found" or response.status_code == 404:
                err_msg = "No shared pages found. Open Notion, go to a page, click '...' -> 'Add connections' -> select OmniScribe to share it."
            else:
                err_msg = f"{response.status_code}: {err_data.get('message', response.text[:200])}"
        except Exception:
            if "object_not_found" in err_msg or response.status_code == 404:
                err_msg = "No shared pages found. Open Notion, go to a page, click '...' -> 'Add connections' -> select OmniScribe to share it."
            else:
                err_msg = f"{response.status_code}: {err_msg[:200]}"
        return {"success": False, "error": err_msg}


# ── JIRA ──────────────────────────────────────────────────────────────────────

def push_to_jira(tickets: list, session_id: str) -> dict:
    """
    Create Jira issues from generated tickets.
    Requires: JIRA_URL, JIRA_EMAIL, JIRA_TOKEN, JIRA_PROJECT_KEY in .env
    Get token: id.atlassian.com/manage-profile/security/api-tokens
    JIRA_URL example: https://yourcompany.atlassian.net
    JIRA_PROJECT_KEY example: OG or DEV or whatever your board key is
    """
    from backend.vault import get_oauth_token

    tok = get_oauth_token("jira")
    if not tok:
        return {"success": False, "error": "Jira not connected. Use the Connections tab."}
    access_token = tok["access_token"]
    extra = json.loads(tok.get("extra_data") or "{}")
    cloud_id = extra.get("cloud_id", "")
    jira_url = f"https://api.atlassian.com/ex/jira/{cloud_id}"
    project = os.getenv("JIRA_PROJECT_KEY", "OG")

    # Dynamic Project Fallback: Gather all available project keys to support automatic failover retry
    keys = [project]
    try:
        proj_resp = requests.get(
            f"{jira_url}/rest/api/3/project",
            headers={"Authorization": f"Bearer {access_token}", "Accept": "application/json"},
            timeout=10
        )
        if proj_resp.status_code == 200:
            proj_list = proj_resp.json()
            if isinstance(proj_list, list) and len(proj_list) > 0:
                available_keys = [p.get("key") for p in proj_list if p.get("key")]
                if project in available_keys:
                    available_keys.remove(project)
                    available_keys.insert(0, project)
                keys = available_keys
    except Exception:
        pass

    priority_map = {"P1": "Highest", "P2": "High", "P3": "Medium"}
    type_map = {"feature": "Story", "bug": "Bug", "task": "Task", "refactor": "Task"}

    created = []
    failed = []
    token_refreshed = False
    active_project_index = 0

    for ticket in tickets:
        created_successfully = False

        while active_project_index < len(keys):
            current_project = keys[active_project_index]
            allowed_types = []

            # Fetch allowed issueTypes for current target project key
            try:
                details_resp = requests.get(
                    f"{jira_url}/rest/api/3/project/{current_project}",
                    headers={"Authorization": f"Bearer {access_token}", "Accept": "application/json"},
                    timeout=10
                )
                if details_resp.status_code == 200:
                    p_details = details_resp.json()
                    allowed_types = [t.get("name") for t in p_details.get("issueTypes", []) if not t.get("subtask")]
            except Exception:
                pass

            mapped_type = type_map.get(ticket.get("ticket_type", "task"), "Task")
            if allowed_types:
                if mapped_type not in allowed_types:
                    mapped_type = allowed_types[0]

            payload = {
                "fields": {
                    "project": {"key": current_project},
                    "summary": f"[{ticket.get('id','')}] {ticket['title']}",
                    "description": {
                        "type": "doc", "version": 1,
                        "content": [
                            {"type": "paragraph", "content": [
                                {"type": "text", "text": ticket["description"]}
                            ]},
                            {"type": "paragraph", "content": [
                                {"type": "text", "text": f"\nAcceptance criteria: {ticket.get('acceptance_criteria','Not specified')}",
                                 "marks": [{"type": "em"}]}
                            ]},
                            {"type": "paragraph", "content": [
                                {"type": "text", "text": f"\n— Generated by OmniScribe Gatekeeper · Session {session_id}",
                                 "marks": [{"type": "subsup", "attrs": {"type": "sub"}}]}
                            ]}
                        ]
                    },
                    "issuetype": {"name": mapped_type},
                    "priority": {"name": priority_map.get(ticket.get("priority", "P2"), "Medium")}
                }
            }

            if ticket.get("assignee") and ticket["assignee"] != "Unassigned":
                payload["fields"]["assignee"] = {"name": ticket["assignee"]}

            headers = {"Authorization": f"Bearer {access_token}", "Content-Type": "application/json"}
            response = requests.post(
                f"{jira_url}/rest/api/3/issue",
                headers=headers,
                json=payload
            )

            # Detect OAuth token expiration
            if response.status_code == 401:
                if not tok.get("refresh_token"):
                    failed.append({
                        "title": ticket["title"],
                        "error": "Jira unauthorized. Please reconnect Jira in the Connections tab to authorize offline sync access."
                    })
                    break
                elif not token_refreshed:
                    from backend.vault import refresh_jira_token
                    new_token = refresh_jira_token()
                    if new_token:
                        access_token = new_token
                        token_refreshed = True
                        headers = {"Authorization": f"Bearer {access_token}", "Content-Type": "application/json"}
                        response = requests.post(
                            f"{jira_url}/rest/api/3/issue",
                            headers=headers,
                            json=payload
                        )
                    else:
                        failed.append({
                            "title": ticket["title"],
                            "error": "Jira unauthorized. Please reconnect Jira in the Connections tab to authorize offline sync access."
                        })
                        break

            # Handle response
            if response.status_code in (200, 201):
                data = response.json()
                created.append({"key": data.get("key"), "title": ticket["title"]})
                created_successfully = True
                break
            else:
                # Self-Healing: If it's a project permission/existence issue, retry with next project key
                err_text = response.text
                is_proj_err = "project" in err_text.lower() or response.status_code == 400
                if is_proj_err and active_project_index < len(keys) - 1:
                    active_project_index += 1
                    continue
                else:
                    err_msg = response.text[:100]
                    try:
                        err_data = response.json()
                        if "errorMessages" in err_data and err_data["errorMessages"]:
                            err_msg = err_data["errorMessages"][0]
                        elif "errors" in err_data and err_data["errors"]:
                            err_msg = str(list(err_data["errors"].values())[0])
                    except Exception:
                        pass
                    failed.append({"title": ticket["title"], "error": f"{response.status_code}: {err_msg}"})
                    break

    res = {
        "success": len(created) > 0,
        "created": created,
        "failed": failed,
        "total": len(tickets)
    }
    if not res["success"] and failed:
        res["error"] = failed[0]["error"]
    return res


# ── GITHUB ────────────────────────────────────────────────────────────────────

def push_to_github(tickets: list, stubs: list, session_id: str) -> dict:
    """
    Create GitHub Issues with Codex stubs attached as code comments.
    Requires: GITHUB_TOKEN and GITHUB_REPO in .env
    Get token: github.com/settings/tokens → Generate new token → repo scope
    GITHUB_REPO format: username/repository-name
    """
    from backend.vault import get_oauth_token

    tok = get_oauth_token("github")
    if not tok:
        return {"success": False, "error": "GitHub not connected. Use the Connections tab."}
    token = tok["access_token"]
    repo = os.getenv("GITHUB_REPO", "")

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json"
    }

    stub_map = {s["ticket_id"]: s["stub_code"] for s in stubs}
    label_map = {"P1": "priority: critical", "P2": "priority: high", "P3": "priority: medium"}
    created = []
    last_error = None

    for ticket in tickets:
        stub = stub_map.get(ticket.get("id", ""), "")
        stub_section = ""
        if stub:
            stub_section = f"\n\n## Codex Generated Stub\n\n```python\n{stub}\n```"

        body = f"""## Description
{ticket['description']}

## Acceptance Criteria
{ticket.get('acceptance_criteria', 'Not specified')}

## Details
| Field | Value |
|-------|-------|
| Ticket ID | `{ticket.get('id','')}` |
| Priority | **{ticket.get('priority','P2')}** |
| Type | {ticket.get('ticket_type','task')} |
| Assignee | {ticket.get('assignee','Unassigned')} |
| Deadline | {ticket.get('deadline','Not specified')} |
{stub_section}

---
*Generated by OmniScribe Gatekeeper · Session `{session_id}` · Secrets sanitized locally*
"""
        labels = [label_map.get(ticket.get("priority", "P2"), "priority: medium"), ticket.get("ticket_type", "task")]

        response = requests.post(
            f"https://api.github.com/repos/{repo}/issues",
            headers=headers,
            json={
                "title": f"[{ticket.get('id','')}] {ticket['title']}",
                "body": body,
                "labels": labels
            }
        )

        if response.status_code == 201:
            data = response.json()
            created.append({"number": data["number"], "url": data["html_url"], "title": ticket["title"]})
        else:
            # Retry without labels if the first request failed (e.g. 403 due to label management permissions)
            response_retry = requests.post(
                f"https://api.github.com/repos/{repo}/issues",
                headers=headers,
                json={
                    "title": f"[{ticket.get('id','')}] {ticket['title']}",
                    "body": body
                }
            )
            if response_retry.status_code == 201:
                data = response_retry.json()
                created.append({"number": data["number"], "url": data["html_url"], "title": ticket["title"]})
            else:
                try:
                    err_data = response_retry.json()
                    last_error = f"{response_retry.status_code}: {err_data.get('message', response_retry.text)}"
                except Exception:
                    last_error = f"{response_retry.status_code}: {response_retry.text[:100]}"

    res = {"success": len(created) > 0, "created": created, "total": len(tickets)}
    if not res["success"] and last_error:
        res["error"] = last_error
    return res


# ── SLACK ─────────────────────────────────────────────────────────────────────

def push_to_slack(brief_content: str, tickets: list, session_id: str) -> dict:
    """
    Post meeting summary to a Slack channel.
    Requires: SLACK_BOT_TOKEN and SLACK_CHANNEL_ID in .env
    Get token: api.slack.com/apps → Create app → OAuth → Bot token
    SLACK_CHANNEL_ID: right-click channel in Slack → View channel details → ID at bottom
    """
    from backend.vault import get_oauth_token

    tok = get_oauth_token("slack")
    if not tok:
        return {"success": False, "error": "Slack not connected. Use the Connections tab."}
    token = tok["access_token"]
    channel = os.getenv("SLACK_CHANNEL_ID", "")

    p1 = [t for t in tickets if t.get("priority") == "P1"]
    p2 = [t for t in tickets if t.get("priority") == "P2"]
    p3 = [t for t in tickets if t.get("priority") == "P3"]

    ticket_lines = ""
    for t in tickets[:8]:
        icon = {"P1": "🔴", "P2": "🟠", "P3": "🟡"}.get(t.get("priority","P2"),"⚪")
        ticket_lines += f"• {icon} *[{t.get('id','')}]* {t['title']} — _{t.get('assignee','Unassigned')}_\n"

    blocks = [
        {"type": "header", "text": {"type": "plain_text", "text": f"📋 Meeting Brief — {datetime.now().strftime('%d %b %Y')}"}},
        {"type": "section", "text": {"type": "mrkdwn", "text": f"*Session:* `{session_id}`"}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn", "text": f"*Summary*\n{brief_content[:300]}..."}},
        {"type": "divider"},
        {"type": "section", "text": {"type": "mrkdwn",
            "text": f"*Action Items ({len(tickets)} total)*\n{ticket_lines}"}},
        {"type": "context", "elements": [
            {"type": "mrkdwn",
             "text": f"🛡 Generated by *OmniScribe Gatekeeper* · {len(p1)} critical · {len(p2)} high · {len(p3)} normal · Secrets sanitized locally"}
        ]}
    ]

    response = requests.post(
        "https://slack.com/api/chat.postMessage",
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        json={"channel": channel, "blocks": blocks, "text": f"Meeting Brief — {session_id}"}
    )

    data = response.json()
    if data.get("ok"):
        return {"success": True, "ts": data.get("ts"), "channel": data.get("channel")}
    return {"success": False, "error": data.get("error", "Unknown error")}

